// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Eleven19.Elm.Syntax")>]
[<assembly: AssemblyProductAttribute("Eleven19.Elm.Syntax")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-05-01T00:00:00.0000000+00:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha")>]
[<assembly: AssemblyMetadataAttribute("GitHash","67a2db2e2757f6d721419398ef5c543a66f30157")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Eleven19.Elm.Syntax"
    let [<Literal>] AssemblyProduct = "Eleven19.Elm.Syntax"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-05-01T00:00:00.0000000+00:00"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyInformationalVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha"
    let [<Literal>] AssemblyMetadata_GitHash = "67a2db2e2757f6d721419398ef5c543a66f30157"
